import type { Notification } from "@/types";

export const MOCK_NOTIFICATIONS: Notification[] = [
  {
    id: "notif-1",
    kind: "reply",
    title: "New reply on your discussion",
    body: "yuki-tomoda replied to 'Best practices for MCP server caching' on Official MCP Servers",
    href: "/r/official-mcp-servers",
    read: false,
    createdAt: "2026-04-08T14:30:00Z",
  },
  {
    id: "notif-2",
    kind: "publish",
    title: "New from a creator you follow",
    body: "helena-costa published 'Zero-Config MCP Bridge' — a new MCP Server",
    href: "/r/zero-config-mcp-bridge",
    read: false,
    createdAt: "2026-04-08T11:00:00Z",
  },
  {
    id: "notif-3",
    kind: "milestone",
    title: "Your item hit 100 installs",
    body: "Claude Superpowers Skills reached 100 verified installs",
    href: "/r/claude-superpowers-skills",
    read: false,
    createdAt: "2026-04-07T18:00:00Z",
  },
  {
    id: "notif-4",
    kind: "update",
    title: "Item you use was updated",
    body: "Awesome CursorRules updated to v2.4.0 — 12 new framework rulesets",
    href: "/r/awesome-cursorrules",
    read: true,
    createdAt: "2026-04-07T09:00:00Z",
  },
  {
    id: "notif-5",
    kind: "reply",
    title: "Your review was marked helpful",
    body: "3 people found your review on GitHub MCP Server helpful",
    href: "/r/github-mcp-server",
    read: true,
    createdAt: "2026-04-06T16:00:00Z",
  },
  {
    id: "notif-6",
    kind: "follow",
    title: "New follower",
    body: "samuel-adeyemi started following you",
    href: "/u/samuel-adeyemi",
    read: true,
    createdAt: "2026-04-06T10:00:00Z",
  },
  {
    id: "notif-7",
    kind: "publish",
    title: "New from Anthropic Skills",
    body: "anthropic-skills published 'Claude Code TDD Skill' — a new Skill",
    href: "/r/claude-code-tdd-skill",
    read: true,
    createdAt: "2026-04-05T14:00:00Z",
  },
  {
    id: "notif-8",
    kind: "milestone",
    title: "Reputation level up",
    body: "You reached Contributor level (50+ reputation)",
    href: "/dashboard/overview",
    read: true,
    createdAt: "2026-04-04T12:00:00Z",
  },
];
