import type { FeatureRequest } from "@/types";

const REF = new Date("2026-04-08T12:00:00Z").getTime();
function ts(daysAgo: number) {
  return new Date(REF - daysAgo * 86_400_000).toISOString();
}

export const MOCK_FEATURE_REQUESTS: FeatureRequest[] = [
  // --- Open (10) ---
  {
    id: "req-1",
    title: "Diff view for ruleset version comparisons",
    description:
      "When a ruleset updates, I want to see exactly what changed between versions. A side-by-side diff like GitHub would help me decide whether to update.",
    author: { username: "alex-rivera", avatarUrl: null },
    voteCount: 89,
    status: "open",
    claimedBy: null,
    linkedRulesetSlug: null,
    tags: ["ux", "versioning"],
    commentCount: 12,
    createdAt: ts(2),
  },
  {
    id: "req-2",
    title: "Bulk install via CLI",
    description:
      "I maintain a team setup with 15 rulesets. Installing one at a time is tedious. A `rulesell install --from lockfile` command would save hours.",
    author: { username: "ravi-prasad", avatarUrl: null },
    voteCount: 67,
    status: "open",
    claimedBy: null,
    linkedRulesetSlug: null,
    tags: ["cli", "productivity"],
    commentCount: 8,
    createdAt: ts(5),
  },
  {
    id: "req-3",
    title: "Private rulesets for organizations",
    description:
      "We need to share proprietary rulesets within our org without making them public. Access control by team membership.",
    author: { username: "samuel-adeyemi", avatarUrl: null },
    voteCount: 112,
    status: "open",
    claimedBy: null,
    linkedRulesetSlug: null,
    tags: ["enterprise", "access-control"],
    commentCount: 18,
    createdAt: ts(8),
  },
  {
    id: "req-4",
    title: "AI-assisted ruleset generation from codebase",
    description:
      "Point it at a repo, it analyzes patterns, coding style, and conventions, then generates a .cursorrules file. Could be a killer feature for onboarding.",
    author: { username: "priya-menon", avatarUrl: null },
    voteCount: 145,
    status: "open",
    claimedBy: null,
    linkedRulesetSlug: null,
    tags: ["ai", "generation", "onboarding"],
    commentCount: 24,
    createdAt: ts(12),
  },
  {
    id: "req-5",
    title: "Webhook notifications for ruleset updates",
    description:
      "Ping my Slack/Discord when a ruleset I depend on releases a new version. Critical for teams that pin versions.",
    author: { username: "helena-costa", avatarUrl: null },
    voteCount: 43,
    status: "open",
    claimedBy: null,
    linkedRulesetSlug: null,
    tags: ["notifications", "integrations"],
    commentCount: 5,
    createdAt: ts(6),
  },
  {
    id: "req-6",
    title: "Composable ruleset layers",
    description:
      "A way to import and extend rulesets like CSS inheritance. Base rules + project-specific overrides without copy-pasting.",
    author: { username: "marc-beaulieu", avatarUrl: null },
    voteCount: 78,
    status: "open",
    claimedBy: null,
    linkedRulesetSlug: null,
    tags: ["architecture", "composability"],
    commentCount: 14,
    createdAt: ts(9),
  },
  {
    id: "req-7",
    title: "Community-driven translations for rulesets",
    description:
      "Many rulesets are English-only. Allow community members to submit translations with a review flow.",
    author: { username: "lukas-weber", avatarUrl: null },
    voteCount: 31,
    status: "open",
    claimedBy: null,
    linkedRulesetSlug: null,
    tags: ["i18n", "community"],
    commentCount: 6,
    createdAt: ts(4),
  },
  {
    id: "req-8",
    title: "Ruleset analytics for creators",
    description:
      "Creators should see: install count by environment, geographic distribution, retention rate (how many keep it installed after 30 days).",
    author: { username: "noa-bar-lev", avatarUrl: null },
    voteCount: 56,
    status: "open",
    claimedBy: null,
    linkedRulesetSlug: null,
    tags: ["analytics", "creators"],
    commentCount: 9,
    createdAt: ts(7),
  },
  {
    id: "req-9",
    title: "Dark mode toggle for code previews",
    description:
      "Code preview blocks use a fixed light theme. I work in dark mode 100% of the time. At minimum, respect the system theme.",
    author: { username: "claire-dubois", avatarUrl: null },
    voteCount: 38,
    status: "open",
    claimedBy: null,
    linkedRulesetSlug: null,
    tags: ["ux", "theming"],
    commentCount: 4,
    createdAt: ts(3),
  },
  {
    id: "req-10",
    title: "Dependency graph for bundles",
    description:
      "When installing a bundle, show a visual graph of which rulesets depend on each other and their compatibility status.",
    author: { username: "daniel-ohta", avatarUrl: null },
    voteCount: 24,
    status: "open",
    claimedBy: null,
    linkedRulesetSlug: null,
    tags: ["bundles", "visualization"],
    commentCount: 3,
    createdAt: ts(1),
  },
  // --- Claimed (5) ---
  {
    id: "req-11",
    title: "VS Code extension for RuleSell",
    description:
      "Install, preview, and manage rulesets directly from the VS Code sidebar. No CLI needed for basic operations.",
    author: { username: "finn-oconnor", avatarUrl: null },
    voteCount: 92,
    status: "claimed",
    claimedBy: "emeka-chukwu",
    linkedRulesetSlug: null,
    tags: ["vscode", "extension", "integration"],
    commentCount: 16,
    createdAt: ts(15),
  },
  {
    id: "req-12",
    title: "Automated quality scoring breakdown",
    description:
      "Show creators how each quality metric is calculated with actionable tips to improve. Currently it is a black box.",
    author: { username: "yuki-tomoda", avatarUrl: null },
    voteCount: 54,
    status: "claimed",
    claimedBy: "priya-menon",
    linkedRulesetSlug: null,
    tags: ["quality", "transparency"],
    commentCount: 7,
    createdAt: ts(10),
  },
  {
    id: "req-13",
    title: "GitHub Actions for ruleset CI/CD",
    description:
      "A GitHub Action that validates, tests, and publishes rulesets to RuleSell on push. Like npm publish but for AI configs.",
    author: { username: "ravi-prasad", avatarUrl: null },
    voteCount: 71,
    status: "claimed",
    claimedBy: "samuel-adeyemi",
    linkedRulesetSlug: null,
    tags: ["ci-cd", "github", "automation"],
    commentCount: 11,
    createdAt: ts(14),
  },
  {
    id: "req-14",
    title: "Interactive ruleset playground",
    description:
      "Test a ruleset against a sample codebase before installing. Like a sandbox where you can see how the AI behaves with those rules.",
    author: { username: "marc-beaulieu", avatarUrl: null },
    voteCount: 83,
    status: "claimed",
    claimedBy: "helena-costa",
    linkedRulesetSlug: null,
    tags: ["playground", "testing", "ux"],
    commentCount: 13,
    createdAt: ts(18),
  },
  {
    id: "req-15",
    title: "Ruleset compatibility matrix",
    description:
      "Show which environments and model versions each ruleset has been tested with. Crowdsourced from user reports.",
    author: { username: "claire-dubois", avatarUrl: null },
    voteCount: 46,
    status: "claimed",
    claimedBy: "daniel-ohta",
    linkedRulesetSlug: null,
    tags: ["compatibility", "environments"],
    commentCount: 8,
    createdAt: ts(11),
  },
  // --- Completed (3) ---
  {
    id: "req-16",
    title: "One-click install for Claude Code skills",
    description:
      "A single command that downloads the skill and configures it in Claude Code. Currently requires manual setup with 5+ steps.",
    author: { username: "alex-rivera", avatarUrl: null },
    voteCount: 134,
    status: "completed",
    claimedBy: "yuki-tomoda",
    linkedRulesetSlug: "senior-engineer-cursor-rules",
    tags: ["cli", "claude-code", "installation"],
    commentCount: 22,
    createdAt: ts(30),
  },
  {
    id: "req-17",
    title: "Quality score badges on listings",
    description:
      "Visual badges (A/B/C grade) on ruleset cards so users can quickly assess quality without opening the detail page.",
    author: { username: "priya-menon", avatarUrl: null },
    voteCount: 98,
    status: "completed",
    claimedBy: "finn-oconnor",
    linkedRulesetSlug: "react-component-architecture",
    tags: ["quality", "ux", "badges"],
    commentCount: 15,
    createdAt: ts(25),
  },
  {
    id: "req-18",
    title: "Verified creator program",
    description:
      "A verification system for creators that have demonstrated expertise. Helps buyers trust the source.",
    author: { username: "samuel-adeyemi", avatarUrl: null },
    voteCount: 156,
    status: "completed",
    claimedBy: "alex-rivera",
    linkedRulesetSlug: "api-design-best-practices",
    tags: ["trust", "creators", "verification"],
    commentCount: 28,
    createdAt: ts(35),
  },
  // --- Declined (2) ---
  {
    id: "req-19",
    title: "AI-generated reviews",
    description:
      "Automatically generate a review of each ruleset using AI. Would provide immediate feedback for new uploads.",
    author: { username: "lukas-weber", avatarUrl: null },
    voteCount: 12,
    status: "declined",
    claimedBy: null,
    linkedRulesetSlug: null,
    tags: ["ai", "reviews"],
    commentCount: 9,
    createdAt: ts(20),
  },
  {
    id: "req-20",
    title: "Anonymous publishing",
    description:
      "Allow publishing rulesets without a username. Some creators want to share without attribution.",
    author: { username: "emeka-chukwu", avatarUrl: null },
    voteCount: 8,
    status: "declined",
    claimedBy: null,
    linkedRulesetSlug: null,
    tags: ["privacy", "publishing"],
    commentCount: 14,
    createdAt: ts(22),
  },
];
