import type { GitHubRepo, GitHubTreeEntry, GitHubSyncStatus } from "@/types";

// -----------------------------------------------------------------------------
// 20 mock GitHub repos
// -----------------------------------------------------------------------------

export const MOCK_GITHUB_REPOS: GitHubRepo[] = [
  // ── 5 from verified orgs ──
  {
    id: "gh-1",
    owner: "anthropic",
    name: "claude-code-rules",
    fullName: "anthropic/claude-code-rules",
    description: "Official Claude Code rules for safe, structured AI coding sessions.",
    starCount: 12400,
    language: "TypeScript",
    license: "MIT",
    lastCommitAt: "2026-04-09T14:22:00Z",
    defaultBranch: "main",
    isPrivate: false,
    org: {
      name: "Anthropic",
      verified: true,
      avatarUrl: "https://avatars.githubusercontent.com/u/76263028",
    },
  },
  {
    id: "gh-2",
    owner: "openai",
    name: "chatgpt-system-prompts",
    fullName: "openai/chatgpt-system-prompts",
    description: "Curated system prompts for ChatGPT custom instructions and plugins.",
    starCount: 8700,
    language: "JSON",
    license: "Apache-2.0",
    lastCommitAt: "2026-04-08T09:15:00Z",
    defaultBranch: "main",
    isPrivate: false,
    org: {
      name: "OpenAI",
      verified: true,
      avatarUrl: "https://avatars.githubusercontent.com/u/14957082",
    },
  },
  {
    id: "gh-3",
    owner: "vercel",
    name: "ai-sdk-rules",
    fullName: "vercel/ai-sdk-rules",
    description: "Cursor/Windsurf rules for the Vercel AI SDK ecosystem.",
    starCount: 5300,
    language: "TypeScript",
    license: "MIT",
    lastCommitAt: "2026-04-07T18:44:00Z",
    defaultBranch: "main",
    isPrivate: false,
    org: {
      name: "Vercel",
      verified: true,
      avatarUrl: "https://avatars.githubusercontent.com/u/14985020",
    },
  },
  {
    id: "gh-4",
    owner: "getcursor",
    name: "cursor-rules-collection",
    fullName: "getcursor/cursor-rules-collection",
    description: "Community-approved .cursorrules files for popular stacks.",
    starCount: 3900,
    language: "TypeScript",
    license: "MIT",
    lastCommitAt: "2026-04-06T11:30:00Z",
    defaultBranch: "main",
    isPrivate: false,
    org: {
      name: "Cursor",
      verified: true,
      avatarUrl: "https://avatars.githubusercontent.com/u/126759922",
    },
  },
  {
    id: "gh-5",
    owner: "cline",
    name: "cline-agent-configs",
    fullName: "cline/cline-agent-configs",
    description: "Pre-built agent configurations for Cline IDE automation.",
    starCount: 2100,
    language: "JSON",
    license: "MIT",
    lastCommitAt: "2026-04-05T16:00:00Z",
    defaultBranch: "main",
    isPrivate: false,
    org: {
      name: "Cline",
      verified: true,
      avatarUrl: "https://avatars.githubusercontent.com/u/163659562",
    },
  },

  // ── 10 personal repos ──
  {
    id: "gh-6",
    owner: "devmaster42",
    name: "fullstack-cursor-rules",
    fullName: "devmaster42/fullstack-cursor-rules",
    description: "Production-ready .cursorrules for Next.js + tRPC + Prisma stacks.",
    starCount: 1850,
    language: "TypeScript",
    license: "MIT",
    lastCommitAt: "2026-04-09T08:10:00Z",
    defaultBranch: "main",
    isPrivate: false,
  },
  {
    id: "gh-7",
    owner: "aibuilder",
    name: "mcp-postgres-schema",
    fullName: "aibuilder/mcp-postgres-schema",
    description: "MCP server that exposes your PostgreSQL schema to Claude.",
    starCount: 920,
    language: "TypeScript",
    license: "Apache-2.0",
    lastCommitAt: "2026-04-08T22:00:00Z",
    defaultBranch: "main",
    isPrivate: false,
  },
  {
    id: "gh-8",
    owner: "prompthacker",
    name: "prompt-library",
    fullName: "prompthacker/prompt-library",
    description: "200+ categorized system prompts for coding, writing, and analysis.",
    starCount: 3400,
    language: "JSON",
    license: "CC-BY-4.0",
    lastCommitAt: "2026-04-07T14:20:00Z",
    defaultBranch: "main",
    isPrivate: false,
  },
  {
    id: "gh-9",
    owner: "n8nwizard",
    name: "n8n-ai-workflows",
    fullName: "n8nwizard/n8n-ai-workflows",
    description: "Plug-and-play n8n workflows for AI automation pipelines.",
    starCount: 670,
    language: "JSON",
    license: "MIT",
    lastCommitAt: "2026-04-06T09:45:00Z",
    defaultBranch: "main",
    isPrivate: false,
  },
  {
    id: "gh-10",
    owner: "codealchemy",
    name: "python-agent-kit",
    fullName: "codealchemy/python-agent-kit",
    description: "CrewAI + LangGraph agent definitions for Python backends.",
    starCount: 440,
    language: "Python",
    license: "MIT",
    lastCommitAt: "2026-04-05T20:30:00Z",
    defaultBranch: "main",
    isPrivate: false,
  },
  {
    id: "gh-11",
    owner: "rulesmith",
    name: "windsurf-cascade-rules",
    fullName: "rulesmith/windsurf-cascade-rules",
    description: "Rules for Windsurf Cascade editor — TypeScript, React, Tailwind.",
    starCount: 280,
    language: "TypeScript",
    license: "MIT",
    lastCommitAt: "2026-04-04T13:15:00Z",
    defaultBranch: "main",
    isPrivate: false,
  },
  {
    id: "gh-12",
    owner: "secops-ai",
    name: "security-audit-rules",
    fullName: "secops-ai/security-audit-rules",
    description: "AI coding rules focused on OWASP Top 10 and secure defaults.",
    starCount: 1200,
    language: "TypeScript",
    license: "Apache-2.0",
    lastCommitAt: "2026-04-03T17:00:00Z",
    defaultBranch: "main",
    isPrivate: false,
  },
  {
    id: "gh-13",
    owner: "solodev99",
    name: "obsidian-ai-templates",
    fullName: "solodev99/obsidian-ai-templates",
    description: "Obsidian vault templates with AI-assisted note-taking prompts.",
    starCount: 150,
    language: null,
    license: "CC0-1.0",
    lastCommitAt: "2026-04-02T10:00:00Z",
    defaultBranch: "main",
    isPrivate: false,
  },
  {
    id: "gh-14",
    owner: "dataeng",
    name: "make-scenario-pack",
    fullName: "dataeng/make-scenario-pack",
    description: "Make.com blueprint collection for data engineering pipelines.",
    starCount: 90,
    language: "JSON",
    license: null,
    lastCommitAt: "2026-04-01T08:30:00Z",
    defaultBranch: "main",
    isPrivate: false,
  },
  {
    id: "gh-15",
    owner: "devmaster42",
    name: "private-company-rules",
    fullName: "devmaster42/private-company-rules",
    description: "Internal coding standards and agent configs. Company use only.",
    starCount: 0,
    language: "TypeScript",
    license: null,
    lastCommitAt: "2026-04-09T12:00:00Z",
    defaultBranch: "main",
    isPrivate: true,
  },

  // ── 5 already claimed (linked to existing mock rulesets) ──
  {
    id: "gh-16",
    owner: "anthropic",
    name: "claude-mcp-starter",
    fullName: "anthropic/claude-mcp-starter",
    description: "Starter template for building MCP servers with TypeScript.",
    starCount: 6200,
    language: "TypeScript",
    license: "MIT",
    lastCommitAt: "2026-04-09T10:00:00Z",
    defaultBranch: "main",
    isPrivate: false,
    org: {
      name: "Anthropic",
      verified: true,
      avatarUrl: "https://avatars.githubusercontent.com/u/76263028",
    },
  },
  {
    id: "gh-17",
    owner: "devmaster42",
    name: "react-cursor-rules",
    fullName: "devmaster42/react-cursor-rules",
    description: "Opinionated .cursorrules for React 19 + Next.js 15 projects.",
    starCount: 2800,
    language: "TypeScript",
    license: "MIT",
    lastCommitAt: "2026-04-08T15:00:00Z",
    defaultBranch: "main",
    isPrivate: false,
  },
  {
    id: "gh-18",
    owner: "aibuilder",
    name: "claude-code-skills",
    fullName: "aibuilder/claude-code-skills",
    description: "A curated set of Claude Code skills for everyday development.",
    starCount: 1600,
    language: "TypeScript",
    license: "MIT",
    lastCommitAt: "2026-04-07T20:00:00Z",
    defaultBranch: "main",
    isPrivate: false,
  },
  {
    id: "gh-19",
    owner: "prompthacker",
    name: "chatgpt-mega-prompts",
    fullName: "prompthacker/chatgpt-mega-prompts",
    description: "Battle-tested ChatGPT system prompts with real usage data.",
    starCount: 4500,
    language: "JSON",
    license: "CC-BY-4.0",
    lastCommitAt: "2026-04-06T12:00:00Z",
    defaultBranch: "main",
    isPrivate: false,
  },
  {
    id: "gh-20",
    owner: "n8nwizard",
    name: "n8n-lead-gen",
    fullName: "n8nwizard/n8n-lead-gen",
    description: "Complete lead generation workflow bundle for n8n.",
    starCount: 340,
    language: "JSON",
    license: "MIT",
    lastCommitAt: "2026-04-05T08:00:00Z",
    defaultBranch: "main",
    isPrivate: false,
  },
];

// Repos that are already linked to existing mock rulesets
export const CLAIMED_REPOS: Record<string, string> = {
  "anthropic/claude-mcp-starter": "rs-mcp-starter",
  "devmaster42/react-cursor-rules": "rs-react-cursor",
  "aibuilder/claude-code-skills": "rs-claude-skills",
  "prompthacker/chatgpt-mega-prompts": "rs-mega-prompts",
  "n8nwizard/n8n-lead-gen": "rs-n8n-leads",
};

// -----------------------------------------------------------------------------
// Mock file trees for 5 repos
// -----------------------------------------------------------------------------

export const MOCK_FILE_TREES: Record<string, GitHubTreeEntry[]> = {
  "anthropic/claude-code-rules": [
    { path: "README.md", type: "file", size: 4200 },
    { path: "LICENSE", type: "file", size: 1100 },
    { path: "rules/", type: "dir", size: 0 },
    { path: "rules/general.md", type: "file", size: 2800 },
    { path: "rules/typescript.md", type: "file", size: 3100 },
    { path: "rules/security.md", type: "file", size: 1900 },
    { path: "rules/testing.md", type: "file", size: 1500 },
    { path: "examples/", type: "dir", size: 0 },
    { path: "examples/nextjs-project.md", type: "file", size: 800 },
    { path: "examples/python-api.md", type: "file", size: 650 },
  ],
  "vercel/ai-sdk-rules": [
    { path: "README.md", type: "file", size: 3800 },
    { path: "LICENSE", type: "file", size: 1100 },
    { path: ".cursorrules", type: "file", size: 2200 },
    { path: "src/", type: "dir", size: 0 },
    { path: "src/ai-sdk-core.md", type: "file", size: 1800 },
    { path: "src/streaming.md", type: "file", size: 1400 },
    { path: "src/tool-calling.md", type: "file", size: 1200 },
  ],
  "devmaster42/fullstack-cursor-rules": [
    { path: "README.md", type: "file", size: 5600 },
    { path: ".cursorrules", type: "file", size: 4100 },
    { path: "variants/", type: "dir", size: 0 },
    { path: "variants/nextjs.md", type: "file", size: 2400 },
    { path: "variants/trpc.md", type: "file", size: 1800 },
    { path: "variants/prisma.md", type: "file", size: 1500 },
  ],
  "prompthacker/prompt-library": [
    { path: "README.md", type: "file", size: 7200 },
    { path: "LICENSE", type: "file", size: 800 },
    { path: "coding/", type: "dir", size: 0 },
    { path: "coding/react-expert.json", type: "file", size: 3200 },
    { path: "coding/python-senior.json", type: "file", size: 2800 },
    { path: "writing/", type: "dir", size: 0 },
    { path: "writing/blog-post.json", type: "file", size: 1500 },
    { path: "analysis/", type: "dir", size: 0 },
    { path: "analysis/data-analyst.json", type: "file", size: 2100 },
  ],
  "aibuilder/mcp-postgres-schema": [
    { path: "README.md", type: "file", size: 3400 },
    { path: "package.json", type: "file", size: 900 },
    { path: "tsconfig.json", type: "file", size: 350 },
    { path: "src/", type: "dir", size: 0 },
    { path: "src/index.ts", type: "file", size: 4600 },
    { path: "src/schema-reader.ts", type: "file", size: 2200 },
    { path: "src/mcp-handler.ts", type: "file", size: 3100 },
  ],
};

// -----------------------------------------------------------------------------
// Mock sync statuses (for rulesets that have a GitHub link)
// -----------------------------------------------------------------------------

export const MOCK_SYNC_STATUSES: Record<string, GitHubSyncStatus> = {
  "rs-mcp-starter": {
    rulesetId: "rs-mcp-starter",
    repoFullName: "anthropic/claude-mcp-starter",
    lastSyncAt: "2026-04-09T12:30:00Z",
    status: "synced",
    pendingChanges: 0,
  },
  "rs-react-cursor": {
    rulesetId: "rs-react-cursor",
    repoFullName: "devmaster42/react-cursor-rules",
    lastSyncAt: "2026-04-08T18:00:00Z",
    status: "outdated",
    pendingChanges: 3,
  },
  "rs-claude-skills": {
    rulesetId: "rs-claude-skills",
    repoFullName: "aibuilder/claude-code-skills",
    lastSyncAt: "2026-04-07T10:00:00Z",
    status: "error",
    pendingChanges: 0,
  },
  "rs-mega-prompts": {
    rulesetId: "rs-mega-prompts",
    repoFullName: "prompthacker/chatgpt-mega-prompts",
    lastSyncAt: "2026-04-09T14:00:00Z",
    status: "synced",
    pendingChanges: 0,
  },
  "rs-n8n-leads": {
    rulesetId: "rs-n8n-leads",
    repoFullName: "n8nwizard/n8n-lead-gen",
    lastSyncAt: "2026-04-05T10:00:00Z",
    status: "outdated",
    pendingChanges: 1,
  },
};
