import type { QAQuestion, QAAnswer } from "@/types";

const REF = new Date("2026-04-08T12:00:00Z").getTime();
function ts(daysAgo: number) {
  return new Date(REF - daysAgo * 86_400_000).toISOString();
}

export const MOCK_QA_QUESTIONS: QAQuestion[] = [
  {
    id: "qa-1",
    title: "How to handle .cursorrules conflicts in monorepos?",
    body: "We have a Turborepo with 12 packages. Each team wants their own .cursorrules. Currently we concatenate at build time but it is fragile. What is the best pattern?",
    author: { username: "alex-rivera", avatarUrl: null, reputation: 245 },
    tags: ["cursor", "monorepo", "configuration"],
    voteCount: 34,
    answerCount: 3,
    viewCount: 412,
    acceptedAnswerId: "qa-1-a1",
    createdAt: ts(2),
  },
  {
    id: "qa-2",
    title: "MCP server authentication with OAuth2?",
    body: "I need my MCP server to authenticate against our corporate IDP (Okta). The MCP spec doesn't seem to cover auth flows. Has anyone implemented this?",
    author: { username: "helena-costa", avatarUrl: null, reputation: 189 },
    tags: ["mcp", "oauth", "security"],
    voteCount: 28,
    answerCount: 2,
    viewCount: 356,
    acceptedAnswerId: "qa-2-a1",
    createdAt: ts(3),
  },
  {
    id: "qa-3",
    title: "Claude Code skill vs system prompt — when to use which?",
    body: "I have been writing system prompts for everything but just discovered Claude Code skills. What is the practical difference? When should I migrate?",
    author: { username: "marc-beaulieu", avatarUrl: null, reputation: 167 },
    tags: ["claude-code", "skills", "prompts"],
    voteCount: 42,
    answerCount: 4,
    viewCount: 623,
    acceptedAnswerId: "qa-3-a2",
    createdAt: ts(5),
  },
  {
    id: "qa-4",
    title: "Rate limiting strategies for Context7 in CI?",
    body: "Our CI runs 200+ parallel jobs. Each calls Context7 for doc lookup. We are hitting rate limits. What caching layer works best?",
    author: { username: "ravi-prasad", avatarUrl: null, reputation: 134 },
    tags: ["context7", "ci-cd", "rate-limiting"],
    voteCount: 19,
    answerCount: 2,
    viewCount: 278,
    acceptedAnswerId: "qa-4-a2",
    createdAt: ts(7),
  },
  {
    id: "qa-5",
    title: "Windsurf rules vs Cursor rules — are they interchangeable?",
    body: "Can I use the same .cursorrules file in Windsurf or do I need to adapt? The documentation is unclear on format differences.",
    author: { username: "lukas-weber", avatarUrl: null, reputation: 98 },
    tags: ["windsurf", "cursor", "compatibility"],
    voteCount: 31,
    answerCount: 3,
    viewCount: 445,
    acceptedAnswerId: "qa-5-a1",
    createdAt: ts(4),
  },
  {
    id: "qa-6",
    title: "How to version control AI agent configurations?",
    body: "Our CrewAI agents have configs that drift between environments. Git is awkward for JSON blobs. What do teams use for agent config management?",
    author: { username: "emeka-chukwu", avatarUrl: null, reputation: 112 },
    tags: ["agents", "version-control", "crewai"],
    voteCount: 22,
    answerCount: 2,
    viewCount: 198,
    acceptedAnswerId: "qa-6-a1",
    createdAt: ts(8),
  },
  {
    id: "qa-7",
    title: "Testing AI-generated code quality — metrics that matter?",
    body: "Beyond pass/fail tests, what metrics do you track for AI code quality? Looking for something more nuanced than 'it compiles'.",
    author: { username: "priya-menon", avatarUrl: null, reputation: 287 },
    tags: ["testing", "quality", "metrics"],
    voteCount: 38,
    answerCount: 5,
    viewCount: 534,
    acceptedAnswerId: "qa-7-a3",
    createdAt: ts(6),
  },
  {
    id: "qa-8",
    title: "Best practices for prompt injection defense in production?",
    body: "We ship a customer-facing AI feature. What are proven defenses against prompt injection beyond basic input sanitization?",
    author: { username: "samuel-adeyemi", avatarUrl: null, reputation: 203 },
    tags: ["security", "prompt-injection", "production"],
    voteCount: 45,
    answerCount: 4,
    viewCount: 712,
    acceptedAnswerId: "qa-8-a1",
    createdAt: ts(9),
  },
  {
    id: "qa-9",
    title: "n8n webhook reliability — handling retries and dedup?",
    body: "Webhooks occasionally fire twice. Our n8n workflow creates duplicate records. Is there a built-in deduplication mechanism?",
    author: { username: "noa-bar-lev", avatarUrl: null, reputation: 156 },
    tags: ["n8n", "webhooks", "reliability"],
    voteCount: 16,
    answerCount: 2,
    viewCount: 189,
    acceptedAnswerId: "qa-9-a1",
    createdAt: ts(11),
  },
  {
    id: "qa-10",
    title: "How to benchmark different AI coding assistants fairly?",
    body: "I want to compare Cursor, Claude Code, and Copilot on our codebase. What methodology avoids confirmation bias and gives actionable results?",
    author: { username: "daniel-ohta", avatarUrl: null, reputation: 178 },
    tags: ["benchmarking", "comparison", "methodology"],
    voteCount: 29,
    answerCount: 3,
    viewCount: 401,
    acceptedAnswerId: "qa-10-a2",
    createdAt: ts(10),
  },
  // --- Unanswered questions ---
  {
    id: "qa-11",
    title: "Gemini CLI integration with custom MCP servers?",
    body: "Has anyone gotten Gemini CLI to work with custom MCP servers? The docs only mention official integrations. Looking for a working example.",
    author: { username: "finn-oconnor", avatarUrl: null, reputation: 145 },
    tags: ["gemini", "mcp", "integration"],
    voteCount: 12,
    answerCount: 0,
    viewCount: 87,
    acceptedAnswerId: null,
    createdAt: ts(1),
  },
  {
    id: "qa-12",
    title: "Obsidian vault as context source for Claude?",
    body: "I want Claude to reference my Obsidian vault during coding sessions. The vault has 2000+ notes. What is the most token-efficient approach?",
    author: { username: "claire-dubois", avatarUrl: null, reputation: 123 },
    tags: ["obsidian", "claude", "knowledge-base"],
    voteCount: 18,
    answerCount: 0,
    viewCount: 134,
    acceptedAnswerId: null,
    createdAt: ts(1),
  },
  {
    id: "qa-13",
    title: "Docker-based MCP server sandboxing — performance impact?",
    body: "Running MCP servers in Docker adds 200-400ms per tool call. Is there a lighter sandbox that maintains security?",
    author: { username: "emeka-chukwu", avatarUrl: null, reputation: 112 },
    tags: ["docker", "mcp", "performance", "security"],
    voteCount: 8,
    answerCount: 0,
    viewCount: 56,
    acceptedAnswerId: null,
    createdAt: ts(2),
  },
  {
    id: "qa-14",
    title: "Multi-language ruleset bundles — best structure?",
    body: "Building a bundle with rules for TypeScript, Python, and Rust. Should I use one file with sections or separate files per language?",
    author: { username: "lukas-weber", avatarUrl: null, reputation: 98 },
    tags: ["bundles", "multi-language", "structure"],
    voteCount: 6,
    answerCount: 0,
    viewCount: 42,
    acceptedAnswerId: null,
    createdAt: ts(0),
  },
  {
    id: "qa-15",
    title: "Aider + RuleSell CLI — can they work together?",
    body: "I use Aider for pair programming. Can I pipe RuleSell assets into Aider's context? Looking for integration patterns.",
    author: { username: "marc-beaulieu", avatarUrl: null, reputation: 167 },
    tags: ["aider", "cli", "integration"],
    voteCount: 10,
    answerCount: 0,
    viewCount: 68,
    acceptedAnswerId: null,
    createdAt: ts(0),
  },
];

export const MOCK_QA_ANSWERS: QAAnswer[] = [
  // qa-1 answers
  {
    id: "qa-1-a1",
    questionId: "qa-1",
    body: "Use a root .cursorrules with shared conventions, then per-package overrides via symlinks. Cursor follows symlinks since v0.42. We do this across 8 packages with zero conflicts.",
    author: { username: "yuki-tomoda", avatarUrl: null, reputation: 312 },
    voteCount: 22,
    isAccepted: true,
    createdAt: ts(2),
  },
  {
    id: "qa-1-a2",
    questionId: "qa-1",
    body: "We use a build script that merges package-level rules into the root file. Works but feels hacky. The symlink approach sounds cleaner.",
    author: { username: "priya-menon", avatarUrl: null, reputation: 287 },
    voteCount: 8,
    isAccepted: false,
    createdAt: ts(1),
  },
  {
    id: "qa-1-a3",
    questionId: "qa-1",
    body: "There is an RFC for multi-file .cursorrules support. Track it at github.com/getcursor/cursor/issues/2847.",
    author: { username: "finn-oconnor", avatarUrl: null, reputation: 145 },
    voteCount: 5,
    isAccepted: false,
    createdAt: ts(1),
  },
  // qa-2 answers
  {
    id: "qa-2-a1",
    questionId: "qa-2",
    body: "Wrap the MCP server in a reverse proxy that handles OAuth2 token exchange. The MCP client sends a Bearer token in the initial handshake, the proxy validates against Okta. We ship this pattern in production.",
    author: { username: "samuel-adeyemi", avatarUrl: null, reputation: 203 },
    voteCount: 18,
    isAccepted: true,
    createdAt: ts(2),
  },
  {
    id: "qa-2-a2",
    questionId: "qa-2",
    body: "MCP transport auth is coming in the spec. For now, the proxy approach is the way. We use Caddy for this.",
    author: { username: "ravi-prasad", avatarUrl: null, reputation: 134 },
    voteCount: 7,
    isAccepted: false,
    createdAt: ts(2),
  },
  // qa-3 answers
  {
    id: "qa-3-a1",
    questionId: "qa-3",
    body: "System prompts are universal — any model reads them. Skills are Claude Code-specific with hooks, tool permissions, and structured output. Use prompts for model-agnostic rules, skills for Claude Code automation.",
    author: { username: "yuki-tomoda", avatarUrl: null, reputation: 312 },
    voteCount: 14,
    isAccepted: false,
    createdAt: ts(4),
  },
  {
    id: "qa-3-a2",
    questionId: "qa-3",
    body: "Skills give you: 1) trigger conditions (when to activate), 2) tool restrictions, 3) structured output templates, 4) composability with other skills. If you need any of those, migrate. If it is just 'write code in this style', a system prompt is fine.",
    author: { username: "priya-menon", avatarUrl: null, reputation: 287 },
    voteCount: 28,
    isAccepted: true,
    createdAt: ts(4),
  },
  {
    id: "qa-3-a3",
    questionId: "qa-3",
    body: "I migrated 15 prompts to skills. Productivity jumped because skills auto-activate. No more copy-pasting prompts.",
    author: { username: "samuel-adeyemi", avatarUrl: null, reputation: 203 },
    voteCount: 11,
    isAccepted: false,
    createdAt: ts(3),
  },
  {
    id: "qa-3-a4",
    questionId: "qa-3",
    body: "One gotcha: skills run in Claude Code only. If you also use Cursor/Copilot, keep a system prompt version too.",
    author: { username: "claire-dubois", avatarUrl: null, reputation: 123 },
    voteCount: 9,
    isAccepted: false,
    createdAt: ts(3),
  },
  // qa-4 answers
  {
    id: "qa-4-a1",
    questionId: "qa-4",
    body: "We tried Redis but the overhead was not worth it for our scale.",
    author: { username: "helena-costa", avatarUrl: null, reputation: 189 },
    voteCount: 4,
    isAccepted: false,
    createdAt: ts(6),
  },
  {
    id: "qa-4-a2",
    questionId: "qa-4",
    body: "Filesystem cache with content-addressable hashing. Key = SHA256(query + lib version). TTL 24h. Dropped our Context7 calls from 200/run to ~15. Implementation is 40 lines of Node.",
    author: { username: "daniel-ohta", avatarUrl: null, reputation: 178 },
    voteCount: 14,
    isAccepted: true,
    createdAt: ts(6),
  },
  // qa-5 answers
  {
    id: "qa-5-a1",
    questionId: "qa-5",
    body: "Windsurf reads .windsurfrules and .cursorrules (fallback). The syntax is 95% compatible. Main difference: Windsurf supports cascade sections that Cursor ignores. Safe to use the same file if you avoid Windsurf-specific features.",
    author: { username: "finn-oconnor", avatarUrl: null, reputation: 145 },
    voteCount: 20,
    isAccepted: true,
    createdAt: ts(3),
  },
  {
    id: "qa-5-a2",
    questionId: "qa-5",
    body: "I maintain both. It is not that much extra work and each tool evolves its format.",
    author: { username: "marc-beaulieu", avatarUrl: null, reputation: 167 },
    voteCount: 6,
    isAccepted: false,
    createdAt: ts(3),
  },
  {
    id: "qa-5-a3",
    questionId: "qa-5",
    body: "RuleSell handles this with variants. One ruleset, multiple environment-specific files.",
    author: { username: "alex-rivera", avatarUrl: null, reputation: 245 },
    voteCount: 12,
    isAccepted: false,
    createdAt: ts(2),
  },
  // qa-6 answers
  {
    id: "qa-6-a1",
    questionId: "qa-6",
    body: "Treat agent configs like IaC. Store as YAML, validate with JSON Schema, diff-friendly. We use a custom CLI that renders YAML to the JSON blobs each platform expects. Git history is clean.",
    author: { username: "priya-menon", avatarUrl: null, reputation: 287 },
    voteCount: 16,
    isAccepted: true,
    createdAt: ts(7),
  },
  {
    id: "qa-6-a2",
    questionId: "qa-6",
    body: "We use Pulumi for agent infra. Config is TypeScript, versioned, type-safe. Overkill for small setups but essential at scale.",
    author: { username: "samuel-adeyemi", avatarUrl: null, reputation: 203 },
    voteCount: 9,
    isAccepted: false,
    createdAt: ts(7),
  },
  // qa-7 answers
  {
    id: "qa-7-a1",
    questionId: "qa-7",
    body: "We track: test pass rate, type coverage delta, lint violation count, and cyclomatic complexity change.",
    author: { username: "helena-costa", avatarUrl: null, reputation: 189 },
    voteCount: 10,
    isAccepted: false,
    createdAt: ts(5),
  },
  {
    id: "qa-7-a2",
    questionId: "qa-7",
    body: "SonarQube's cognitive complexity metric is the best I have found. AI code tends to be flat but verbose.",
    author: { username: "daniel-ohta", avatarUrl: null, reputation: 178 },
    voteCount: 8,
    isAccepted: false,
    createdAt: ts(5),
  },
  {
    id: "qa-7-a3",
    questionId: "qa-7",
    body: "Three metrics: 1) First-run correctness (does the generated code pass existing tests without edits), 2) Review delta (lines changed during human review), 3) Regression rate (bugs introduced within 7 days). We track all three per-model and per-ruleset.",
    author: { username: "yuki-tomoda", avatarUrl: null, reputation: 312 },
    voteCount: 26,
    isAccepted: true,
    createdAt: ts(5),
  },
  {
    id: "qa-7-a4",
    questionId: "qa-7",
    body: "Add 'human readability' — we survey devs on whether they'd merge the AI PR without changes. Subjective but revealing.",
    author: { username: "claire-dubois", avatarUrl: null, reputation: 123 },
    voteCount: 12,
    isAccepted: false,
    createdAt: ts(4),
  },
  {
    id: "qa-7-a5",
    questionId: "qa-7",
    body: "Token efficiency matters too. A 500-token prompt that produces the same quality as a 2000-token one is objectively better.",
    author: { username: "ravi-prasad", avatarUrl: null, reputation: 134 },
    voteCount: 7,
    isAccepted: false,
    createdAt: ts(4),
  },
  // qa-8 answers
  {
    id: "qa-8-a1",
    questionId: "qa-8",
    body: "Layer defense: 1) Input validation + length limits, 2) Separate system/user message boundaries, 3) Output classifier that detects policy violations, 4) Canary tokens in the system prompt that trigger alerts if echoed. We run all four in production. Zero successful injections in 6 months.",
    author: { username: "yuki-tomoda", avatarUrl: null, reputation: 312 },
    voteCount: 32,
    isAccepted: true,
    createdAt: ts(8),
  },
  {
    id: "qa-8-a2",
    questionId: "qa-8",
    body: "Do not forget: rate limiting per user session. Many injection attempts are iterative — they try variations until one works.",
    author: { username: "helena-costa", avatarUrl: null, reputation: 189 },
    voteCount: 14,
    isAccepted: false,
    createdAt: ts(8),
  },
  {
    id: "qa-8-a3",
    questionId: "qa-8",
    body: "Anthropic's constitutional AI approach is worth studying. Build your own constitution — list of things the model must never do.",
    author: { username: "priya-menon", avatarUrl: null, reputation: 287 },
    voteCount: 11,
    isAccepted: false,
    createdAt: ts(7),
  },
  {
    id: "qa-8-a4",
    questionId: "qa-8",
    body: "We use a shadow model to evaluate responses before sending to the user. Adds 200ms but catches edge cases.",
    author: { username: "samuel-adeyemi", avatarUrl: null, reputation: 203 },
    voteCount: 8,
    isAccepted: false,
    createdAt: ts(7),
  },
  // qa-9 answers
  {
    id: "qa-9-a1",
    questionId: "qa-9",
    body: "Use an idempotency key. Hash the webhook payload + timestamp (rounded to 5s window). Store in Redis with 1h TTL. If the key exists, skip processing. This handles both retries and genuine duplicates.",
    author: { username: "helena-costa", avatarUrl: null, reputation: 189 },
    voteCount: 12,
    isAccepted: true,
    createdAt: ts(10),
  },
  {
    id: "qa-9-a2",
    questionId: "qa-9",
    body: "n8n has a built-in 'Remove Duplicates' node. Less robust than a proper idempotency layer but works for simple cases.",
    author: { username: "ravi-prasad", avatarUrl: null, reputation: 134 },
    voteCount: 5,
    isAccepted: false,
    createdAt: ts(10),
  },
  // qa-10 answers
  {
    id: "qa-10-a1",
    questionId: "qa-10",
    body: "Randomize the order you test tools. Recency bias is real — the last tool tested often 'feels' best.",
    author: { username: "marc-beaulieu", avatarUrl: null, reputation: 167 },
    voteCount: 7,
    isAccepted: false,
    createdAt: ts(9),
  },
  {
    id: "qa-10-a2",
    questionId: "qa-10",
    body: "Create 20 representative tasks from your actual codebase. Same tasks, same order, same starting state for each tool. Measure: completion rate, edit distance from ideal, wall clock time, and token cost. Blind review by a third dev who did not run the tests. We published our methodology — DM me for the template.",
    author: { username: "priya-menon", avatarUrl: null, reputation: 287 },
    voteCount: 21,
    isAccepted: true,
    createdAt: ts(9),
  },
  {
    id: "qa-10-a3",
    questionId: "qa-10",
    body: "Important caveat: benchmarks decay fast. Re-run monthly as models update. Our rankings shifted 3 times in Q1 2026.",
    author: { username: "yuki-tomoda", avatarUrl: null, reputation: 312 },
    voteCount: 14,
    isAccepted: false,
    createdAt: ts(8),
  },
];
